[package]
distribution = "2201.11.0"
org = "ballerinax"
name = "hubspot.crm.engagements.communications"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "crm", "enagagements communications", "engagements", "communications"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.engagements.communications"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
